const projectsdata = [
    {
        _id:'1',
        name:'Budynek Mieszkalny Wielorodzinny Pod Fortem, Kraków',
        description:'We were responsible for designing all HVAC and sanitary installations inside the building.',
        buildingType:'Residential building',
        localization:'ul. Pod Fortem, Kraków, Poland',
        architect:'Archisystem',
        surface:6800,
        projectStage:'Building and detailed design',
        years:'2017-2019',
        buildingStatus:'In progress',
        picture:'https://drive.google.com/uc?id=1qMjuuP-fS2l3i98JZF_rPIcV96EAxOVo',
        projectScope:[
            'heating',
            'mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat source technology'
        ]
    },
    {
        _id:'2',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/project_photo/wadowicka5_2_jrk72_press_s-1024x683.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'3',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2017/10/Palko-1-1024x433.png',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'4',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2018/11/TK_GH_1-1024x749.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'5',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2019/11/Lema_1-1024x570.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'6',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2019/11/Cracovia.Tenis_.II_01-1024x771.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'7',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2019/11/Chopin_1-1024x626.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'8',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2019/11/Hala-Pr%C3%B3szk%C3%B3w-1024x576.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'9',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2018/11/TK_GH_1-1024x749.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'10',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2019/11/Lema_1-1024x570.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'11',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2019/11/Cracovia.Tenis_.II_01-1024x771.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'12',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Wadowicka, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2019/11/Chopin_1-1024x626.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
    {
        _id:'13',
        name:'Budynek Biurowy Wadowicka, Kraków',
        description:'We were responsible for designing all HVAC installations and sanitary installations inside and outside the building.',
        buildingType:'Residential building',
        localization:'ul. Mala Gora 14B, Kraków, Poland',
        architect:'JRK72',
        surface:4000,
        projectStage:'Building and detailed design',
        years:'2018-2019',
        buildingStatus:'In progress',
        picture:'http://mc2projekty.pl/wp-content/uploads/2019/11/Hala-Pr%C3%B3szk%C3%B3w-1024x576.jpg',
        projectScope:[
            'heating installation',
            'cooling installation',
            'installation of mechanical ventilation',
            'water, sewage and hot utility water installations',
            'heat and cold source technology',
            'fire ventilation system - pressure differential system',
            'water, sewage and heating connections'
        ]
    },
]

module.exports = projectsdata